### ISSUE TITLE
Need to have hasError() methor in WriteResult

### ISSUE THREAD

**Issue by adpande** [vznet/mongo-jackson-mapper#13]
Hi,

I think we need a hasError() method in WriteResult which will return a boolean value. This will enable us to quickly find if the insert has failed.

Thanks & Regards,
Abhishek

**Comment by jroper** [comment]
I think you can use getLastError().ok() to achieve this now.

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
