### ISSUE TITLE
Add support for update(DBObject query, T object)

### ISSUE THREAD

**Issue by vladaman** [vznet/mongo-jackson-mapper#14]
It would be great to have convenience methods to insert/update objects using DBObject as filter.

Suggested behavior:

``` java
UserObject userObject = new UserObject();
userObject.setName("Steve");

Query q2 = DBQuery.is("username", "jsmith");
db.update(q2, userObject);
```

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
