### ISSUE TITLE
Support for $push / $inc?

### ISSUE THREAD

**Issue by bimargulies** [vznet/mongo-jackson-mapper#17]
Is there any way, when mapping to and from Java objects, to do an upsert with $push or $inc or $addToSet?

**Comment by jroper** [comment]
Yes, try

JacksonDBCollection.update(DBQuery.is("_id", id), DBUpdate.push("field1", value1).inc("field2").addToSet("field3", value3), true, false);

First boolean flag is upsert, second is whether multiple records should be updated.

**Comment by bimargulies** [comment]
I was thinking about how to pass a pojo instead of a DBUpdate builder. I was thinking of something like:

```
 update(DBQuery.is(), somePojoJacksonUnderstands, DBObjectToAttach$ModifiersToFields, true, false)
```

I can see it would be a big job.

**Comment by jroper** [comment]
Not 100% sure about your above example, but if you mean just passing in a pojo, and having it use $set on all the non null fields, this isn't quite possible, for example, if you have a nested document, and it has some null fields, should the $set be on the document itself, or on it's fields that a non null?  As for passing in map that contains which modifiers to use for which fields, I would suspect that the code to build the DBUpdate yourself would be just as simple, if not clearer, then building such a map.

**Comment by bimargulies** [comment]
I see your point.
