### ISSUE TITLE
I think I have a bug with addToSet(List<?>)

### ISSUE THREAD

**Issue by bimargulies** [vznet/mongo-jackson-mapper#18]
Using 1.4.0, if I call addToSet with a List<String>, and then call update for an upsert, I end up with something like:

   field: [ [ "string" ] ]

instead of 

  field: [ "string" ]

**Comment by jroper** [comment]
Could you provide some example code that reproduces this bug?  I just added the following test to the Mongo Jackson Mapper test suite, and it passes:

```
@Test
public void testAddToSetListWithUpsert() throws Exception {
    coll.update(new BasicDBObject("_id", "blah"), DBUpdate.addToSet("simpleList", Arrays.asList("hello", "world")), true, false);
    MockObject inserted = coll.findOneById("blah");
    assertThat(inserted.simpleList, hasSize(2));
    assertThat(inserted.simpleList, hasItem("hello"));
    assertThat(inserted.simpleList, hasItem("world"));
}
```

**Comment by bimargulies** [comment]
Yea, I'll get to work on it.

On Thu, Jun 7, 2012 at 6:53 AM, James Roper
reply@reply.github.com
wrote:

**Comment by bimargulies** [comment]
Hmm. It still is not working in my 'real' code with 1.4.2. I end up with objects like the following, using code indistinguishable from the test case I posted for you. Is there a way to run your tests against live mongo? The 'allMentions' below should be a list of strings, not a list of lists of strings.

``` javascript
{ "_id" : ObjectId( "4fd0bb8bfd9d408478e03275" ),
  "allMentions" : [ 
    [ 
      "united states" ], 
    [ 
      "states" ], 
    [ 
      "unites states" ], 
    [ 
      "united" ], 
    [ 
      "united stated" ] ],
  "corefEntityId" : "45-LOCATION",
  "documentCount" : 1701,
  "label" : "United States",
  "type" : "Location" }
```

**Comment by jroper** [comment]
Check which method you are invoking.  There is an addToSet(Object... objects), and addToSet(List<Object> objects).  If you were to, for example, do this:

Object objects = Arrays.asList("one", "two");
DBUpdate.addToSet("field", objects);

then you will be invoking the wrong method, and you will see what you are seeing.  Instead, it should be:

List<String> objects = Arrays.asList("one", "two");
DBUpdate.addToSet("field", objects);

That will work.

**Comment by bimargulies** [comment]
I see what I did. I passed it a Set instead of a list. 

How would you feel about a Set overload, too?

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
