### ISSUE TITLE
Find and retrieve only a subset of array items in document with $slice

### ISSUE THREAD

**Issue by sankalpsaxena81** [vznet/mongo-jackson-mapper#20]
I have implemented versioning on an entity by having an array of entity with in the document
example below:
Preferences docment:

"_id" : ObjectId("4fe5384503647b38b970cadf")
"versions": [ {"color" : "blue","fontSize" : "10"} , {"color" : "green","fontSize" : "20"} ]

query through mongo console :
preferences.find({"_id": ObjectId("4fe5384503647b38b970cadf")},{versions:{$slice: -1}})
result
{"color" : "green","fontSize" : "20"}

How can I use $slice through Mongo-jackson-mapper

**Comment by jroper** [comment]
This can be done like so:

```
coll.findById(objectId, new BasicDBObject("versions", new BasicDBObject("$slice", -1)));
```

The result will be your parent entity, with an array of one element in the versions field.

**Comment by sankalpsaxena81** [comment]
Awesome !!  This is exactly what I was looking for.
Really appreciate your answer!!

On Tue, Jun 26, 2012 at 2:58 AM, James Roper <
reply@reply.github.com

> wrote:
> 
> This can be done like so:
> 
> coll.findById(objectId, new BasicDBObject("versions", new
> BasicDBObject("$slice", -1)));
> 
> The result will be your parent entity, with an array of one element in the
> versions field.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/vznet/mongo-jackson-mapper/issues/20#issuecomment-6571625

## 

Regards,
Sankalp
