### ISSUE TITLE
ObjectCodec not set on DBDecoderBsonParser

### ISSUE THREAD

**Issue by jhhdk** [vznet/mongo-jackson-mapper#29]
As mentioned on user group i have a fairly simple usecase that fails. It apears to be caused by  DBDecoderBsonParser not having its objectCodec set. I dont know how to attach source or patches to issues when submitted, i will be following thread if you need more info.

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
